### ISSUE TITLE
Do weights need to be defined in advance?

### ISSUE THREAD

**Issue by guangingmai** [nitrogenlab/pyompa#10]
Following your codes, the user-defined weights will change and use the weights recalculated by the code. So, do weights need to be defined in advance?

**Comment by AvantiShri** [comment]
Sorry I missed this. Yes, the weights on different parameters need to be chosen by the user. You can stick to the examples provided in the code, but the choice of weights is not a hard science as it is dataset dependent based on how noisy you judge certain measurements to be and how much you trust them to be a reliable readout of water mass mixing.
